services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb1'
      - 'POSTGRES_PASSWORD=varsha'
      - 'POSTGRES_USER=user'
    ports:
      - '5435:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '8888:80'
    depends_on:
      - 'postgres'
volumes:
  postgres_data: